startups <- read.csv("C:/startups.csv", sep=";")
head(startups)
apply(is.na(startups), 2, which)
mean = apply(startups[,c("R.D.Spend","Administration","Marketing.Spend","Profit")],2,
mean)
median = apply(startups[,c("R.D.Spend","Administration","Marketing.Spend","Profit")],2,
median)
sd = apply(startups[,c("R.D.Spend","Administration","Marketing.Spend","Profit")],2,sd) max = apply(startups[,c("R.D.Spend","Administration","Marketing.Spend","Profit")],2,max) min = apply(startups[,c("R.D.Spend","Administration","Marketing.Spend","Profit")],2, min) t(data.frame(mean,median,sd,max,min))
hist(startups$Profit,ylim = c(0,12), xlab ="Profit", main = "Histogram of Profit", labels
= T)
boxplot(Profit~State ,data=startups , main = "Boxplot of Profit for State")
pairs(Profit ~ R.D.Spend,main = "pairs of Profit for R.D.Spend",data=startups) pairs(Profit ~ Administration,main = "pairs of Profit for Administration",data=startups) pairs(Profit~ Marketing.Spend,main = "pairs of Profit for Marketing.Spend",data=startups) New_York<-subset(startups,startups$State =="New York") California<-subset(startups,startups$State =="California") Florida<-subset(startups,startups$State =="Florida")
qqnorm(New_York$Profit)
qqline(New_York$Profit)
shapiro.test(New_York$Profit)
qqnorm(California$Profit)
qqline(California$Profit)
shapiro.test(California$Profit)
qqnorm(Florida$Profit)
qqline(Florida$Profit)
shapiro.test(Florida$Profit)
library(car)
leveneTest(Profit~as.factor(State),data=startups) anova_model<-aov(Profit~as.factor(State),data=startups)
summary(anova_model)
M1 = lm(Profit ~ R.D.Spend + Administration + State + Marketing.Spend, data = startups) summary(M1)
M2 = lm(Profit ~ R.D.Spend + State + Marketing.Spend, data = startups)
summary(M2)
M3 = lm(Profit ~ R.D.Spend + Marketing.Spend, data = startups)
summary(M3)
M4 = lm(Profit ~ R.D.Spend, data = startups)
summary(M4)
anova(M1,M2)
anova(M2,M3)
anova(M3,M4)
plot(M4)
